// See https://aka.ms/new-console-template for more information

using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;
using SolidWorks.Interop.swscanto3d;

/* Display a prompt to the console and wait for the user's input before continuing */
static void PromptAndWait(string prompt)
{
    Console.WriteLine(prompt);
    Console.ReadKey();
}

Console.WriteLine("Welcome to the LASTRO Solidworks Automation Tool!");
Console.WriteLine("Starting SolidWorks Application ...");

SldWorks? solidworksApp;
PartDoc modulePart;

// get solidworks and start it
const string solidWorkAppID = "SldWorks.Application";
solidworksApp = Activator.CreateInstance(Type.GetTypeFromProgID(solidWorkAppID)) as SldWorks;

if (solidworksApp == null)
{
    Console.WriteLine("SolidWorks could not be started. Exiting program now");
    return;
}

solidworksApp.Visible = true;

Console.WriteLine("SolidWorks should appear. If not, there is an error starting solidworks");

/*
 Start modeling
 */


// create part file. Seems fine
PromptAndWait("Press any key to create part");

modulePart = (PartDoc)solidworksApp.INewDocument2(
    solidworksApp.GetUserPreferenceStringValue((int)swUserPreferenceStringValue_e.swDefaultTemplatePart), 0, 0, 0);

// import the point cloud (the grid text file generated by the python script)
// TODO: find out why SolidWorks.Interop.swscanto3d namespace is not in the solidworks interop dll

// wait for user input before closing
PromptAndWait("Press any key to exit");

// close Solidworks that runs in the background
solidworksApp.ExitApp();

