// See https://aka.ms/new-console-template for more information

using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;
using SolidworksAutomationTool;

/* Display a prompt to the console and wait for the user's input before continuing */
static void PromptAndWait(string prompt)
{
    Console.WriteLine(prompt);
    Console.ReadKey();
}

Console.WriteLine("Welcome to the LASTRO Solidworks Automation Tool!");

// import the point cloud (the grid text file generated by the python script)

Console.WriteLine("Reading point cloud file from a defined path ...");
PointCloud pointCloud = new PointCloud();
// TODO: make the txt file's path customizable
pointCloud.ReadPointCloudFromTxt(@"C:\Users\aiden\Desktop\Astrobots\focal_plane_calc\Results\grid_inter.txt");

Console.WriteLine("Completed reading point cloud file");
// DEBUG: check if the points are read in correctly
pointCloud.PrintPoint3Ds();

Console.WriteLine("Starting SolidWorks Application ...");

SldWorks? solidworksApp;
ModelDoc2 modulePart;
Sketch module3DSketch;
SketchManager sketchManager;

// get solidworks and start it
const string solidWorkAppID = "SldWorks.Application";
solidworksApp = Activator.CreateInstance(Type.GetTypeFromProgID(solidWorkAppID)) as SldWorks;

if (solidworksApp == null)
{
    Console.WriteLine("SolidWorks could not be started. Exiting program now");
    return;
}

solidworksApp.Visible = true;
Console.WriteLine("SolidWorks should appear. If not, there is an error starting solidworks");


// create part file. Seems fine
PromptAndWait("Press any key to create part");

/*
 Start modeling
 */

// create a part
modulePart = solidworksApp.INewDocument2( solidworksApp.GetUserPreferenceStringValue((int)swUserPreferenceStringValue_e.swDefaultTemplatePart), 0, 0, 0);

PromptAndWait("Press any key to insert 3D sketch");
modulePart.SketchManager.Insert3DSketch(true);

PromptAndWait("Press any key to create point cloud in sketch");

foreach (Point3D point in pointCloud.point3Ds)
{
    modulePart.SketchManager.CreatePoint( point.x, point.y, point.z );

}
// The documentation says: Inserts a new 3D sketch in a model or closes the active sketch. ?? 
modulePart.SketchManager.Insert3DSketch(true);

// wait for user input before closing
PromptAndWait("Press any key to exit");

// close Solidworks that runs in the background
solidworksApp.ExitApp();